In [1]:
import pandas as pd

In [2]:
fake_df = pd.read_csv("Fake.csv")
true_df = pd.read_csv("True.csv")

# Add labels
fake_df["label"] = 0
true_df["label"] = 1

# Combine
isot_df = pd.concat([fake_df, true_df], ignore_index=True)

# Shuffle randomly
isot_df = isot_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Create a clean serial number
isot_df.insert(0, "id", range(1, len(isot_df) + 1))

display(isot_df.head())
print(isot_df.shape)

,id,title,text,subject,date,label
0,1,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,2,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,3,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,4,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,5,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

(44898, 6)

In [3]:
# Check missing values
print(isot_df.isnull().sum())

id         0
title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [4]:
# Check duplicate rows
print("Duplicate rows:", isot_df.duplicated().sum())

Duplicate rows: 0

In [5]:
# Check label distribution
print("\nLabel distribution:")
print(isot_df["label"].value_counts())

Label distribution:
label
0    23481
1    21417
Name: count, dtype: int64

In [6]:
# Check class percentages
print("\nLabel percentage:")
print(isot_df["label"].value_counts(normalize=True) * 100)

Label percentage:
label
0    52.298543
1    47.701457
Name: proportion, dtype: float64

In [7]:
isot_df["content"] = (
    isot_df["title"].astype(str) + " " +
    isot_df["text"].astype(str)
)

display(isot_df[["title", "text", "content", "label"]].head())

,title,text,content,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",Ben Stein Calls Out 9th Circuit Court: Committ...,0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,Trump drops Steve Bannon from National Securit...,1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,Puerto Rico expects U.S. to lift Jones Act shi...,1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",OOPS: Trump Just Accidentally Confirmed He Le...,0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",Donald Trump heads for Scotland to reopen a go...,1

# Bharat News

In [10]:
bharat_df = pd.read_csv("bharatfakenewskosh.csv")
print("Shape:", bharat_df.shape)
display(bharat_df.head())

Shape: (26232, 19)

,id,Author_Name,Fact_Check_Source,Source_Type,Statement,Eng_Trans_Statement,News Body,Eng_Trans_News_Body,Media_Link,Publish_Date,Fact_Check_Link,News_Category,Language,Region,Platform,Text,Video,Image,Label
0,BFNK_1,Shinjinee Majumder,Alt News,IFCN,फ़ैक्ट-चेक: तेलंगाना में एक रिपोर्टर ने गृह मंत...,Fact-check: A reporter in Telangana stopped sp...,सोशल मीडिया पर एक वीडियो वायरल है जिसमें एक पत...,A video is viral on social media in which a jo...,https://i0.wp.com/www.altnews.in/Hindi/wp-cont...,9th July 2022,https://www.altnews.in/Hindi/fact-check-was-am...,Politics,Hindi,Telangana,Twitter,no,yes,no,False
1,BFNK_2,Kalim Ahmed,Alt News,IFCN,PM मोदी को UAE का सर्वोच्च नागरिक सम्मान मिलने...,Share by stating the old video of PM Modi's hi...,प्रधानमंत्री नरेंद्र मोदी को सोने की चेन से सम...,A video of Prime Minister Narendra Modi being ...,https://i0.wp.com/www.altnews.in/Hindi/wp-cont...,9th July 2022,https://www.altnews.in/Hindi/old-video-of-pm-m...,Politics,Hindi,National,Twitter,no,yes,no,False
2,BFNK_3,Abhishek Kumar,Alt News,IFCN,वायरल तस्वीर में सुप्रीम कोर्ट के जज सूर्यकांत...,Supreme Court judges Suryakant and JB Pardiwal...,बीते दिनों नूपुर शर्मा ने टीवी डिबेट में पैगम्...,"Recently, Nupur Sharma made an objectionable c...",https://i0.wp.com/www.altnews.in/Hindi/wp-cont...,7th July 2022,https://www.altnews.in/Hindi/false-claim-with-...,Politics,Hindi,National,Twitter,no,no,yes,False
3,BFNK_4,Abhishek Kumar,Alt News,IFCN,मीडिया ने दी ग़लत ख़बर: कटनी में मुस्लिम सरपंच क...,Media gave wrong news: After the victory of Mu...,एक वीडियो सोशल मीडिया पर वायरल है. इसे शेयर कर...,A video is viral on social media. While sharin...,https://i0.wp.com/www.altnews.in/Hindi/wp-cont...,5th July 2022,https://www.altnews.in/Hindi/media-misreport-p...,Politics,Hindi,Madhya Pradesh,Twitter,no,no,yes,False
4,BFNK_5,Kinjal,Alt News,IFCN,महिला ने राहुल गांधी को कश्मीर मुद्दे पर मोदी ...,The woman lashed out at Rahul Gandhi to oppose...,सोशल मीडिया पर राहुल गांधी का एक वीडियो वायरल ...,A video of Rahul Gandhi has gone viral on soci...,https://i0.wp.com/www.altnews.in/Hindi/wp-cont...,4th July 2022,https://www.altnews.in/Hindi/2019-video-of-wom...,Politics,Hindi,Kashmir,Twitter,no,yes,no,True

In [11]:
print("Shape:", bharat_df.shape)

print("\nColumns:")
print(bharat_df.columns.tolist())

print("\nLabel distribution:")
print(bharat_df["Label"].value_counts())

print("\nUnique labels:")
print(bharat_df["Label"].unique())

print("\nMissing values:")
print(
    bharat_df[
        ["Eng_Trans_Statement", "Eng_Trans_News_Body", "Label"]
    ].isnull().sum()
)

Shape: (26232, 19)

Columns:
['id', 'Author_Name', 'Fact_Check_Source', 'Source_Type', 'Statement', 'Eng_Trans_Statement', 'News Body', 'Eng_Trans_News_Body', 'Media_Link', 'Publish_Date', 'Fact_Check_Link', 'News_Category', 'Language', 'Region', 'Platform', 'Text', 'Video', 'Image', 'Label']

Label distribution:
Label
True     15913
False    10319
Name: count, dtype: int64

Unique labels:
[False  True]

Missing values:
Eng_Trans_Statement      0
Eng_Trans_News_Body    872
Label                    0
dtype: int64

In [12]:
# Prepare BharatFakeNewsKosh

# Create combined text
bharat_df["content"] = (
    bharat_df["Eng_Trans_Statement"].fillna("").astype(str)
    + " "
    + bharat_df["Eng_Trans_News_Body"].fillna("").astype(str)
).str.strip()

# Convert labels
# False -> 0 (Fake)
# True  -> 1 (Real)
bharat_df["label"] = bharat_df["Label"].astype(int)

# Keep only required columns
bharat_clean = bharat_df[["content", "label"]].copy()

# Check result
print("Bharat dataset shape:", bharat_clean.shape)

print("\nLabel distribution:")
print(bharat_clean["label"].value_counts())

display(bharat_clean.head())

Bharat dataset shape: (26232, 2)

Label distribution:
label
1    15913
0    10319
Name: count, dtype: int64

                                             content  label
0  Fact-check: A reporter in Telangana stopped sp...      0
1  Share by stating the old video of PM Modi's hi...      0
2  Supreme Court judges Suryakant and JB Pardiwal...      0
3  Media gave wrong news: After the victory of Mu...      0
4  The woman lashed out at Rahul Gandhi to oppose...      1

# Combine both dataset (ISOT and Bhartfakenews)

In [14]:
# Combine ISOT and BharatFakeNewsKosh

final_df = pd.concat(
    [
        isot_df[["content", "label"]],
        bharat_clean[["content", "label"]]
    ],
    ignore_index=True
)

# Shuffle all samples
final_df = final_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# Create new sequential ID
final_df.insert(0, "id", range(1, len(final_df) + 1))

print("Final dataset shape:", final_df.shape)

print("\nLabel distribution:")
print(final_df["label"].value_counts())

print("\nLabel percentage:")
print(final_df["label"].value_counts(normalize=True) * 100)

display(final_df.head())

Final dataset shape: (71130, 3)

Label distribution:
label
1    37330
0    33800
Name: count, dtype: int64

Label percentage:
label
1    52.481372
0    47.518628
Name: proportion, dtype: float64

   id                                            content  label
0   1   Trump Had THIS Black Republican Removed From ...      0
1   2  Are the raids actually raided by the IT depart...      0
2   3  Tirur's train from Mumbai The description of t...      1
3   4  Macedonian nationals arrested in Greece over w...      1
4   5  'I can't take this any more:' Rohingya Muslims...      1

# Text preprocessing.

In [18]:
# Inspect raw text examples

for i in range(2):
    print(f"\n--- Sample {i+1} ---")
    print(final_df.loc[i, "content"][:300])

--- Sample 1 ---
 Trump Had THIS Black Republican Removed From A Campaign Event There aren t very many black Republican Party officials in the United States, but somehow one was too many for Donald Trump s presidential campaign at an event in Atlanta.Buzzfeed reports that Michael McNeely, the first vice chair of the

--- Sample 2 ---
Are the raids actually raided by the IT department in Mumbai Municipal Corporation ..? Learn what the truth is… A post was shared on November 14, 2019 by a Facebook user named Bharvi Kumar. “IT raid has been started in Mumbai Municipal Corporation. If you know, there is a Shiv Sena's ritual, so thes

In [19]:
# Text length statistics

text_lengths = final_df["content"].str.len()

print("Minimum length:", text_lengths.min())
print("Maximum length:", text_lengths.max())
print("Average length:", text_lengths.mean())
print("Median length:", text_lengths.median())

Minimum length: 20
Maximum length: 51893
Average length: 1727.1666807254323
Median length: 1059.0

In [20]:
# Check URLs in the dataset

url_count = final_df["content"].str.contains(
    r"http\S+|www\S+",
    regex=True,
    na=False
).sum()

print("Texts containing URLs:", url_count)
print("Percentage:", (url_count / len(final_df)) * 100)

Texts containing URLs: 3466
Percentage: 4.872768170954591

In [26]:
import re

def clean_text(text):
    text = str(text).lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", " ", text)

    # Keep letters, numbers, spaces and apostrophes
    text = re.sub(r"[^a-z0-9\s']", " ", text)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


# Re-clean the dataset
final_df["clean_content"] = final_df["content"].apply(clean_text)

# Remove any newly empty texts
final_df = final_df[
    final_df["clean_content"].str.strip() != ""
].copy()

final_df = final_df.reset_index(drop=True)

print("Dataset shape:", final_df.shape)

Dataset shape: (71121, 4)

In [27]:
# Calculate number of words in each cleaned article
# basically calculating total words and making a fixed length for content
word_lengths = final_df["clean_content"].str.split().str.len()

print("Minimum words:", word_lengths.min())
print("Maximum words:", word_lengths.max())
print("Average words:", word_lengths.mean())
print("Median words:", word_lengths.median())

print("\nPercentiles:")
print(word_lengths.quantile([0.90, 0.95, 0.97, 0.98, 0.99]))

Minimum words: 4
Maximum words: 8389
Average words: 290.6345523825593
Median words: 177.0

Percentiles:
0.90     656.0
0.95     837.0
0.97     951.0
0.98    1068.0
0.99    1322.0
Name: clean_content, dtype: float64

In [28]:
empty_rows = final_df[final_df["clean_content"].str.strip() == ""]

print("Empty cleaned texts:", len(empty_rows))
display(empty_rows.head())

Empty cleaned texts: 0

Empty DataFrame
Columns: [id, content, label, clean_content]
Index: []

In [29]:
# Remove rows with empty cleaned text
final_df = final_df[final_df["clean_content"].str.strip() != ""].copy()

# Reset index
final_df = final_df.reset_index(drop=True)

# Recreate sequential ID
final_df["id"] = range(1, len(final_df) + 1)

print("Final dataset shape:", final_df.shape)
print("Empty texts:", (final_df["clean_content"].str.strip() == "").sum())

Final dataset shape: (71121, 4)
Empty texts: 0

# tokenizer

In [30]:
def tokenize(text):
    return text.split()

# Test
sample = final_df["clean_content"].iloc[0]

print("Text:")
print(sample[:500])

print("\nTokens:")
print(tokenize(sample)[:30])

Text:
trump had this black republican removed from a campaign event there aren t very many black republican party officials in the united states but somehow one was too many for donald trump s presidential campaign at an event in atlanta buzzfeed reports that michael mcneely the first vice chair of the georgia republicans was given the heave ho by team trump michael mcneely the first vice chair of the georgia republicans was escorted out of atlanta s fox theatre by secret service after being told ther

Tokens:
['trump', 'had', 'this', 'black', 'republican', 'removed', 'from', 'a', 'campaign', 'event', 'there', 'aren', 't', 'very', 'many', 'black', 'republican', 'party', 'officials', 'in', 'the', 'united', 'states', 'but', 'somehow', 'one', 'was', 'too', 'many', 'for']

In [31]:
# 1. Duplicate cleaned articles
print("Duplicate cleaned texts:", final_df["clean_content"].duplicated().sum())

# 2. Word count after cleaning
word_counts = final_df["clean_content"].str.split().str.len()

print("\nWord count:")
print("Minimum:", word_counts.min())
print("Maximum:", word_counts.max())
print("Median:", word_counts.median())

# 3. Very short articles
print("\nArticles with <= 5 words:", (word_counts <= 5).sum())
print("Articles with <= 10 words:", (word_counts <= 10).sum())

# 4. Final label distribution
print("\nLabel distribution:")
print(final_df["label"].value_counts())
print("\nLabel percentage:")
print(final_df["label"].value_counts(normalize=True) * 100)

Duplicate cleaned texts: 6944

Word count:
Minimum: 4
Maximum: 8389
Median: 177.0

Articles with <= 5 words: 3
Articles with <= 10 words: 294

Label distribution:
label
1    37330
0    33791
Name: count, dtype: int64

Label percentage:
label
1    52.488013
0    47.511987
Name: proportion, dtype: float64

In [32]:
# Remove duplicate articles based on cleaned text
before = len(final_df)

final_df = final_df.drop_duplicates(
    subset="clean_content",
    keep="first"
).copy()

after_duplicates = len(final_df)

print("Removed duplicate texts:", before - after_duplicates)
print("Remaining articles:", after_duplicates)


# Remove extremely short articles (< 10 words)
word_counts = final_df["clean_content"].str.split().str.len()

before_short = len(final_df)

final_df = final_df[word_counts >= 10].copy()

after_short = len(final_df)

print("Removed short texts:", before_short - after_short)
print("Final articles:", after_short)


# Reset index and recreate ID
final_df = final_df.reset_index(drop=True)
final_df["id"] = range(1, len(final_df) + 1)


# Final check
print("\nFinal shape:", final_df.shape)

print("\nLabel distribution:")
print(final_df["label"].value_counts())

print("\nLabel percentage:")
print(final_df["label"].value_counts(normalize=True) * 100)

Removed duplicate texts: 6944
Remaining articles: 64177
Removed short texts: 162
Final articles: 64015

Final shape: (64015, 4)

Label distribution:
label
1    36194
0    27821
Name: count, dtype: int64

Label percentage:
label
1    56.539873
0    43.460127
Name: proportion, dtype: float64

In [33]:
# Check class distribution after cleaning
print("Final class distribution:")
print(final_df["label"].value_counts())

print("\nFinal class percentage:")
print(
    (final_df["label"].value_counts(normalize=True) * 100)
    .round(2)
)

# Check whether any duplicate cleaned texts remain
print("\nRemaining duplicate texts:",
      final_df["clean_content"].duplicated().sum())

Final class distribution:
label
1    36194
0    27821
Name: count, dtype: int64

Final class percentage:
label
1    56.54
0    43.46
Name: proportion, dtype: float64

Remaining duplicate texts: 0

# Update till now

# 📰 Fake News Detection — Dataset Preparation

### Dataset Preparation Completed

- Combined **ISOT Fake News Dataset** (`Fake.csv` + `True.csv`)
- Assigned labels:
  - `0` → Fake News
  - `1` → Real News
- Combined **BharatFakeNewsKosh** with the ISOT dataset
- Used English-translated statement and news body for BharatFakeNewsKosh
- Created a unified `content` column
- Performed light NLP text preprocessing:
  - Lowercasing
  - URL removal
  - HTML tag removal
  - Special-character cleanup
  - Whitespace normalization
- Removed **URL-only/empty records**
- Removed duplicate articles based on cleaned text
- Removed extremely short texts (<10 words)
- Randomized and reset the dataset index

### Final Dataset

**64,015 unique articles**

```text
├── Real: 36,194 (56.54%)
└── Fake: 27,821 (43.46%)

# train/validation/test split

In [35]:
from sklearn.model_selection import train_test_split

# 80% Training, 20% Temporary
train_df, temp_df = train_test_split(
    final_df,
    test_size=0.20,
    random_state=42,
    stratify=final_df["label"]
)

# Split remaining 20% equally:
# 10% Validation, 10% Test
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42,
    stratify=temp_df["label"]
)

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

print("\nTrain distribution:")
print(train_df["label"].value_counts())
print(train_df["label"].value_counts(normalize=True).round(4))

print("\nValidation distribution:")
print(val_df["label"].value_counts())
print(val_df["label"].value_counts(normalize=True).round(4))

print("\nTest distribution:")
print(test_df["label"].value_counts())
print(test_df["label"].value_counts(normalize=True).round(4))

Train: (51212, 4)
Validation: (6401, 4)
Test: (6402, 4)

Train distribution:
label
1    28955
0    22257
Name: count, dtype: int64
label
1    0.5654
0    0.4346
Name: proportion, dtype: float64

Validation distribution:
label
1    3619
0    2782
Name: count, dtype: int64
label
1    0.5654
0    0.4346
Name: proportion, dtype: float64

Test distribution:
label
1    3620
0    2782
Name: count, dtype: int64
label
1    0.5654
0    0.4346
Name: proportion, dtype: float64

In [36]:
from collections import Counter

# Tokenize training text
train_tokens = train_df["clean_content"].apply(tokenize)

# Count word frequencies
word_counter = Counter()

for tokens in train_tokens:
    word_counter.update(tokens)

print("Total word occurrences:", sum(word_counter.values()))
print("Unique words:", len(word_counter))

print("\nMost common 20 words:")
print(word_counter.most_common(20))

Total word occurrences: 14229124
Unique words: 131799

Most common 20 words:
[('the', 782854), ('to', 397489), ('of', 345653), ('a', 320170), ('and', 292997), ('in', 282417), ('s', 204272), ('that', 178353), ('on', 156888), ('is', 143985), ('for', 127906), ('trump', 106956), ('said', 99192), ('it', 98186), ('he', 96921), ('with', 91203), ('was', 85403), ('as', 78118), ('by', 73070), ('has', 71932)]

Text
 ↓
Tokenization
 ↓
Vocabulary  <---- we are doing this after
 ↓
Integer IDs
 ↓
Embedding
 ↓
RNN

In [37]:
from collections import Counter

# Count word frequencies ONLY in the training data
word_counter = Counter()

for text in train_df["clean_content"]:
    word_counter.update(tokenize(text))

# Vocabulary size
MAX_VOCAB_SIZE = 30000

# Special tokens
PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"

# Reserve 2 positions for special tokens
most_common_words = word_counter.most_common(MAX_VOCAB_SIZE - 2)

# Create word → index mapping
word_to_idx = {
    PAD_TOKEN: 0,
    UNK_TOKEN: 1
}

for idx, (word, _) in enumerate(most_common_words, start=2):
    word_to_idx[word] = idx

# Create index → word mapping
idx_to_word = {
    idx: word
    for word, idx in word_to_idx.items()
}

print("Total unique words in training data:", len(word_counter))
print("Final vocabulary size:", len(word_to_idx))
print("PAD index:", word_to_idx[PAD_TOKEN])
print("UNK index:", word_to_idx[UNK_TOKEN])

print("\nFirst 20 vocabulary entries:")
print(list(word_to_idx.items())[:20])

Total unique words in training data: 131799
Final vocabulary size: 30000
PAD index: 0
UNK index: 1

First 20 vocabulary entries:
[('<PAD>', 0), ('<UNK>', 1), ('the', 2), ('to', 3), ('of', 4), ('a', 5), ('and', 6), ('in', 7), ('s', 8), ('that', 9), ('on', 10), ('is', 11), ('for', 12), ('trump', 13), ('said', 14), ('it', 15), ('he', 16), ('with', 17), ('was', 18), ('as', 19)]

# Embeddings

In [38]:
MAX_LEN = 1000

def text_to_sequence(text):
    tokens = tokenize(text)

    # Convert words to integer IDs
    sequence = [
        word_to_idx.get(token, word_to_idx["<UNK>"])
        for token in tokens
    ]

    # Truncate long articles
    sequence = sequence[:MAX_LEN]

    # Pad short articles
    if len(sequence) < MAX_LEN:
        sequence += [word_to_idx["<PAD>"]] * (MAX_LEN - len(sequence))

    return sequence


# Test on one article
sample_text = train_df["clean_content"].iloc[0]

sample_sequence = text_to_sequence(sample_text)

print("Original words:", len(tokenize(sample_text)))
print("Sequence length:", len(sample_sequence))
print("First 30 token IDs:", sample_sequence[:30])
print("Number of PAD tokens:", sample_sequence.count(word_to_idx["<PAD>"]))

Original words: 62
Sequence length: 1000
First 30 token IDs: [11, 2, 3045, 69, 263, 1873, 10, 6939, 8365, 7, 2141, 1496, 884, 54, 2, 312, 11, 10, 624, 923, 886, 5, 120, 18, 212, 20, 5, 174, 172, 4]
Number of PAD tokens: 938

# Training phase

In [39]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("Running on CPU")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Selected device:", device)

PyTorch version: 2.13.0+cu126
CUDA available: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
CUDA version: 12.6
Selected device: cuda

In [40]:
from torch.utils.data import Dataset, DataLoader
import torch

class FakeNewsDataset(Dataset):
    def __init__(self, dataframe):
        self.texts = dataframe["clean_content"].tolist()
        self.labels = dataframe["label"].astype(int).tolist()

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        sequence = text_to_sequence(self.texts[idx])
        label = self.labels[idx]

        return (
            torch.tensor(sequence, dtype=torch.long),
            torch.tensor(label, dtype=torch.float32)
        )

In [41]:
train_dataset = FakeNewsDataset(train_df)
val_dataset = FakeNewsDataset(val_df)
test_dataset = FakeNewsDataset(test_df)

print("Train samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))
print("Test samples:", len(test_dataset))

Train samples: 51212
Validation samples: 6401
Test samples: 6402

In [42]:
BATCH_SIZE = 32

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("Number of training batches:", len(train_loader))
print("Number of validation batches:", len(val_loader))
print("Number of test batches:", len(test_loader))

Number of training batches: 1601
Number of validation batches: 201
Number of test batches: 201

In [45]:
sample_batch, sample_labels = next(iter(train_loader))

print("Batch shape:", sample_batch.shape)
print("Labels shape:", sample_labels.shape)

print("\nFirst sample:")
print(sample_batch[0][:30])

print("\nFirst 10 labels:")
print(sample_labels[:10])

Batch shape: torch.Size([32, 1000])
Labels shape: torch.Size([32])

First sample:
tensor([  46,  136,  856, 9249,   13, 4717,   73,    8, 2816, 1607,  515,  239,
          47,   56, 3651,    3, 3922,  844,  499,    2, 1607,  515,  239, 6777,
        4859,   21, 8216,    2,  202,    4])

First 10 labels:
tensor([0., 0., 1., 1., 0., 0., 0., 0., 0., 1.])

Input tokens
     ↓
Embedding
     ↓
LSTM / RNN
     ↓
Dropout
     ↓
Fully Connected
     ↓
Sigmoid
     ↓
Fake / Real

# Architecture

In [47]:
import torch
import torch.nn as nn

class FakeNewsLSTM(nn.Module):
    def __init__(
        self,
        vocab_size,
        embedding_dim=128,
        hidden_dim=128,
        num_layers=2,
        dropout=0.3
    ):
        super(FakeNewsLSTM, self).__init__()

        # Convert token IDs into dense vectors
        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim,
            padding_idx=0
        )

        # Bidirectional LSTM
        self.lstm = nn.LSTM(
            input_size=embedding_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout
        )

        # Dropout before classification
        self.dropout = nn.Dropout(dropout)

        # 2 directions × hidden_dim
        self.fc = nn.Linear(hidden_dim * 2, 1)

    def forward(self, x):
        # x: [batch_size, sequence_length]

        embedded = self.embedding(x)
        # [batch_size, sequence_length, embedding_dim]

        output, (hidden, cell) = self.lstm(embedded)

        # Last hidden state from both directions
        forward_hidden = hidden[-2]
        backward_hidden = hidden[-1]

        hidden_combined = torch.cat(
            (forward_hidden, backward_hidden),
            dim=1
        )

        hidden_combined = self.dropout(hidden_combined)

        output = self.fc(hidden_combined)

        return output.squeeze(1)

# Create the model

In [48]:
VOCAB_SIZE = len(word_to_idx)

model = FakeNewsLSTM(
    vocab_size=VOCAB_SIZE,
    embedding_dim=128,
    hidden_dim=128,
    num_layers=2,
    dropout=0.3
)

model = model.to(device)

print(model)

FakeNewsLSTM(
  (embedding): Embedding(30000, 128, padding_idx=0)
  (lstm): LSTM(128, 128, num_layers=2, batch_first=True, dropout=0.3, bidirectional=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=1, bias=True)
)

In [49]:
total_params = sum(
    p.numel() for p in model.parameters()
    if p.requires_grad
)

print(f"Trainable parameters: {total_params:,}")

Trainable parameters: 4,499,713

# Loss function + optimizer

In [50]:
criterion = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

print("Loss function:", criterion)
print("Optimizer:", optimizer)

Loss function: BCEWithLogitsLoss()
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)

In [51]:
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=1
)

In [52]:
# model
import copy
import time

def train_model(model, train_loader, val_loader, criterion, optimizer,
                scheduler, device, epochs=10, patience=3):

    best_val_loss = float("inf")
    best_model_state = copy.deepcopy(model.state_dict())
    patience_counter = 0

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": []
    }

    for epoch in range(epochs):

        start_time = time.time()

        # =========================
        # Training
        # =========================
        model.train()

        total_train_loss = 0
        correct_train = 0
        total_train = 0

        for inputs, labels in train_loader:

            inputs = inputs.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()

            outputs = model(inputs)

            loss = criterion(outputs, labels)

            loss.backward()

            optimizer.step()

            total_train_loss += loss.item()

            predictions = (torch.sigmoid(outputs) >= 0.5).float()

            correct_train += (predictions == labels).sum().item()
            total_train += labels.size(0)

        train_loss = total_train_loss / len(train_loader)
        train_acc = correct_train / total_train

        # =========================
        # Validation
        # =========================
        model.eval()

        total_val_loss = 0
        correct_val = 0
        total_val = 0

        with torch.no_grad():

            for inputs, labels in val_loader:

                inputs = inputs.to(device)
                labels = labels.to(device)

                outputs = model(inputs)

                loss = criterion(outputs, labels)

                total_val_loss += loss.item()

                predictions = (torch.sigmoid(outputs) >= 0.5).float()

                correct_val += (predictions == labels).sum().item()
                total_val += labels.size(0)

        val_loss = total_val_loss / len(val_loader)
        val_acc = correct_val / total_val

        # Learning-rate scheduler
        scheduler.step(val_loss)

        # Save history
        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        elapsed = time.time() - start_time

        print(
            f"Epoch [{epoch+1}/{epochs}] | "
            f"Train Loss: {train_loss:.4f} | "
            f"Train Acc: {train_acc:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val Acc: {val_acc:.4f} | "
            f"Time: {elapsed:.2f}s"
        )

        # =========================
        # Best model checkpoint
        # =========================
        if val_loss < best_val_loss:

            best_val_loss = val_loss
            best_model_state = copy.deepcopy(model.state_dict())

            torch.save(
                model.state_dict(),
                "best_fake_news_lstm.pth"
            )

            patience_counter = 0

            print("  ✓ Best model saved")

        else:

            patience_counter += 1

            print(
                f"  No improvement "
                f"({patience_counter}/{patience})"
            )

            if patience_counter >= patience:

                print("  Early stopping triggered.")
                break

    # Restore best model
    model.load_state_dict(best_model_state)

    print("\nTraining complete.")
    print(f"Best validation loss: {best_val_loss:.4f}")

    return model, history

# Model training and learning

In [53]:
EPOCHS = 10
PATIENCE = 3

model, history = train_model(
    model=model,
    train_loader=train_loader,
    val_loader=val_loader,
    criterion=criterion,
    optimizer=optimizer,
    scheduler=scheduler,
    device=device,
    epochs=EPOCHS,
    patience=PATIENCE
)

Epoch [1/10] | Train Loss: 0.3485 | Train Acc: 0.8073 | Val Loss: 0.3065 | Val Acc: 0.8221 | Time: 98.64s
  ✓ Best model saved
Epoch [2/10] | Train Loss: 0.2792 | Train Acc: 0.8406 | Val Loss: 0.2811 | Val Acc: 0.8330 | Time: 106.39s
  ✓ Best model saved
Epoch [3/10] | Train Loss: 0.2694 | Train Acc: 0.8461 | Val Loss: 0.2808 | Val Acc: 0.8336 | Time: 97.81s
  ✓ Best model saved
Epoch [4/10] | Train Loss: 0.2621 | Train Acc: 0.8523 | Val Loss: 0.2902 | Val Acc: 0.8292 | Time: 97.84s
  No improvement (1/3)
Epoch [5/10] | Train Loss: 0.2525 | Train Acc: 0.8594 | Val Loss: 0.3014 | Val Acc: 0.8311 | Time: 97.34s
  No improvement (2/3)
Epoch [6/10] | Train Loss: 0.2363 | Train Acc: 0.8727 | Val Loss: 0.3455 | Val Acc: 0.8272 | Time: 97.49s
  No improvement (3/3)
  Early stopping triggered.

Training complete.
Best validation loss: 0.2808

# Testing

In [54]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import torch

model.eval()

all_predictions = []
all_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs = inputs.to(device)
        outputs = model(inputs)

        probabilities = torch.sigmoid(outputs)
        predictions = (probabilities >= 0.5).int()

        all_predictions.extend(predictions.cpu().numpy())
        all_labels.extend(labels.int().cpu().numpy())

accuracy = accuracy_score(all_labels, all_predictions)
precision = precision_score(all_labels, all_predictions)
recall = recall_score(all_labels, all_predictions)
f1 = f1_score(all_labels, all_predictions)

print("Test Accuracy :", round(accuracy, 4))
print("Test Precision:", round(precision, 4))
print("Test Recall   :", round(recall, 4))
print("Test F1 Score :", round(f1, 4))

print("\nClassification Report:")
print(classification_report(
    all_labels,
    all_predictions,
    target_names=["Fake", "Real"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(all_labels, all_predictions))

Test Accuracy : 0.8446
Test Precision: 0.789
Test Recall   : 0.9898
Test F1 Score : 0.8781

Classification Report:
              precision    recall  f1-score   support

        Fake       0.98      0.66      0.79      2782
        Real       0.79      0.99      0.88      3620

    accuracy                           0.84      6402
   macro avg       0.88      0.82      0.83      6402
weighted avg       0.87      0.84      0.84      6402


Confusion Matrix:
[[1824  958]
 [  37 3583]]

In [55]:
checkpoint = {
    "model_state_dict": model.state_dict(),
    "word_to_idx": word_to_idx,
    "max_len": MAX_LEN,
    "vocab_size": len(word_to_idx),
    "embedding_dim": 128,
    "hidden_dim": 128,
    "num_layers": 2,
    "bidirectional": True,
    "dropout": 0.3
}

torch.save(
    checkpoint,
    "fake_news_lstm_checkpoint.pth"
)

print("✓ Complete checkpoint saved")
print("Vocabulary size:", len(word_to_idx))
print("Max sequence length:", MAX_LEN)

✓ Complete checkpoint saved
Vocabulary size: 30000
Max sequence length: 1000